### ISSUE TITLE
Artisan commands with docker-compose

### ISSUE THREAD

**Issue by mepoohsta** [hyn/multi-tenant#874] opened 2019-12-11 20:51 UTC
```
        // Create New Website
        $website = new Website;
        app(WebsiteRepository::class)->create($website);

        // associate the website with a hostname
        $hostname = new Hostname;
        $hostname->fqdn = $fqdn;
        app(HostnameRepository::class)->attach($hostname, $website);

        // make hostname current
        app(Environment::class)->tenant($website);



        $process = new Process('sudo docker-compose run php php artisan passport:install');

        $process1 = new Process('sudo docker-compose run php php artisan db:seed');

        $process->run();
        $process1->run();



        $tenant = new Tenant($website, $hostname);
```

This artisan commands not working :(

How can I exec artisan comand on my aws, I don't install php on instance so 
```
        Artisan::call('passport:install');
        Artisan::call('db:seed');
```

Will be not working.

**Comment by fletch3555** [comment] 2019-12-20 19:57
Couple things....

1. The issue is not optional.  Please edit your post to match https://raw.githubusercontent.com/tenancy/multi-tenant/5.x/.github/ISSUE_TEMPLATE/Bug_report.md
2. I'm not quite sure what you're trying to do here...  We definitely need more information.
    1. Is this code snippet in a command? In a controller? Are you running in tinker?
    2. Is it running as part of a containerized app (i.e. is it already in a docker container?)

**Comment by Plytas** [comment] 2020-01-30 21:26
Closing as there wasn't any response from the issue author. If you still require assistance please reopen with the additional requested info, or create a new issue using the provided issue template.

**Closed as completed by Plytas** 2020-01-30 21:26 UTC
