### ISSUE TITLE
How to overwrite the default views files through the multi-tenant folder?

### ISSUE THREAD

**Issue by deleugpn** [hyn/multi-tenant#152] opened 2016-09-14 21:57 UTC
I'm trying to build a Hello World project with 2 customers and see the power of the package for myself, but I'm stuck at the **resources** and **routes** elements now.
## The problem

When accessing my different hostnames (`home.php7.local` and `customer-1.php7.local`), I see `welcome.blade.php` that is located under `hello-world/resources/views/welcome.blade.php`. I tried creating different files under their own storage folder, but no luck so far.
I have one file at `/hello-world/storage/multi-tenant/1-home-php7-/views/welcome.blade.php` and a different one at `/hello-world/storage/multi-tenant/2-customer-1/views/welcome.blade.php`. How do I get them to overwrite the default `welcome.blade.php` located in the `resources/views` folder?

For more information, the next session gives a little background on how I got here.
## Background
- I installed a brand new Cent OS 7 VM from scratch using the minimal iso and Virtual Box (No Vagrant), installed **PHP 7.0**, **MySQL 5.7** and set a shared folder to point to `/var/www/html/`.
- After that, I created a clean Laravel project and installed `hyn/multi-tenant: 2.0.x@dev` through composer.
- I made sure to [Integrate Into Laravel](https://hyn.readme.io/docs/integrate-into-laravel) and [Configure](https://hyn.readme.io/docs/configuration) it following the docs.
- **Note:** _I didn't run the queue at all because I would like to configure Apache myself because when the time for deployment comes, I will be using a cPanel environment. Although I have root access to it, I can't allow third-party libraries to change cPanel Apache configuration files._
## Tenancies

I now have 2 **customers**, 2 **hostnames** and 2 **websites**. One is `home.php7.local` and the other is `customer-1.php7.local`. The following snippet represents the Apache Configuration for **customer-1**, but **home** is pretty similar, changing just the _alias_ value and the _logs_.

```
<VirtualHost *:80>
  ServerName customer-1.php7.local
  DocumentRoot "/var/www/html/hello-world/public/"
  alias "/media/" "/var/www/html/hello-world/storage/multi-tenant/2-customer-1/media/"
  <Directory "/var/www/html/hello-world/public/">
    Options Indexes FollowSymlinks MultiViews
    AllowOverride All
    Require all granted
  </Directory>
  ErrorLog "/var/log/httpd/error-customer-1-hello-world.log"
  ServerSignature Off
  CustomLog "/var/log/httpd/access-home-customer-1-world.log" combined
</VirtualHost>
```

**Comment by luceos** [comment] 2016-09-14 23:55
Currently the tenant view path does not have a higher priority over the system-wide view path. This is caused by using `addLocation` on the `FileViewFinder` which simply appends another location to search for views. A solution would be to make this configurable and allow for namespacing, pre- or appending the location. From the top of the brain I think I decided for this approach because a) I hate namespaced views and b) prepending is not easy to do.

**Comment by deleugpn** [comment] 2016-09-15 00:58
After reading your comment, I just erased the system-wide file `resources/views/welcome.blade.php` and that was enough to have each `welcome.blade.php` being shown by their respective domain. Although it is sad to know that I can't work on generalized views system-wide and add customization views on a tenant-level, it was **really** nice to know that I did everything correctly.

My migrations are still empty, so my next step will be to create some tables and watch it working with separation of data. I also want to investigate the implementation of Dingo API generalized for all tenants. 

Feel free to close this if you don't intend to support generalized/customized views or make it a future enhancement. Either way, at least I know I'm making progress with the package. Thank you very much.

I might reply to this topic if I come up with anything to achieve this. From the top of my head, I was thinking about making usage of symbolic link and hope the chmod 777 of a symbolic link doesn't screw anything over.

**Comment by luceos** [comment] 2016-09-15 06:53
I think making view loading configurable is something I'd like to have. So no worries it will be in there, just not sure prepending will be an option then.

Can you explain how you want to solve this with symbolic links?

**Comment by deleugpn** [comment] 2016-09-15 11:08
My thought is to never have view files under the system-wide folder `resources/views/` and come up with a new separate folder `whatever/views`. From the system perspective, those views don't even exists. So every tenant that will inherit the standard view file would have a symbolic link at `storage/multi-tenant/<tenant>/` pointing to the respective file in `whatever/views`. If a tenant buys customization, I would create the same file manually at their own tenant folder, allowing me to have customized content in that file. 

I haven't tried it yet, but I know that a symbolic link is a fake-file that consist of permission 777, which is enough condition to get blocked by suPHP, for instance. I don't know if the view files in a Laravel project gets to be interpreted by PHP and if suPHP will allow Apache to invoke the file anyway.

If at any point you implement a way to have the tenant files to overwrite the original files, I can just copy `whatever/views` into `resources/views` and erase all symbolic links and possibly re-enable suPHP. I'm assuming the very existence of a file in a tenant folder is enough to overwrite the system-wide, after all, the goal to have a system-wide file is to write standard software and the goal for the tenant view folders would be freedom to customize.

**Closed as completed** 2016-10-05 07:28 UTC
