### ISSUE TITLE
Postgresql compatibility with version 2.x

### ISSUE THREAD

**Issue by jdbolts** [hyn/multi-tenant#179] opened 2016-12-20 12:05 UTC
I'm currently unable to connect to create a tenant as the system states that password authentication failed for the given user.

I can see that this stems from the package using the website as the database user dynamically. However, when i check my postgres installation i cannot see any newly created users.
Below is the command which fails:
` php artisan migrate --tenant=all`

![image](https://cloud.githubusercontent.com/assets/8181433/21349929/8c5803f8-c6ac-11e6-8321-5be2a452851b.png)

Any help on this would be much appreciated. Thanks.

**Comment by luceos** [comment] 2016-12-20 13:27
The package revolves around MySQL, not PGSQL. Although I understand that might be a very good alternative database driver. Are you sure you've given the system connection the rights to create users? This has been documented [here](https://hyn.readme.io/docs/configuration):

```sql
grant all privileges on *.* to 'hyn'@'localhost' with grant option;
```
Seems postgres should be able to do the same thing: https://www.postgresql.org/docs/9.0/static/sql-grant.html

**Comment by jdbolts** [comment] 2016-12-20 13:56
I have tried various different user privileges within Postgresql. i currently have a user set up with the following user privileges:
`Superuser, Create role, Create DB, Replication`

However, this is not an ideal scenario to have these user privileges.

Also, PostgreSql user 'roles' instead of 'users' although these work in the same way. It could be possible that this could be affecting the way this is working.

Would it be possible to amend the package to allow for PgSql installations?

**Comment by luceos** [comment] 2016-12-20 14:01
Assuming your schema is called public:

```sql
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO hyn;
```

I think there are hardly any restrictions to the database driver already, the only requirement is either a root user or a privileged user to create and manage other users.

Related to your concern about security with these privileges, it's sadly the only way of allowing tenancy databases to be separated. My documentation always suggests installing this package with Laravel on its own dedicated (virtual) machine.

**Comment by jdbolts** [comment] 2016-12-20 14:14
I have granted all privileges to the database user and tried again however the same issue is occurring.

I have followed the documentation and cannot seem to see what the problem is. I can see that all files and folders are created after running this command:
```php
sudo php artisan multi-tenant:setup --customer=EXAMPLE --email=foo@example.com --hostname=example.com --webserver=(nginx|apache|no)
```

However, there is no database created either.

**Comment by luceos** [comment] 2016-12-20 14:17
The cause is the system connection. Your user does not have alleviated rights. Did you try using the root database user, `postgres` in this case? You have to do some tuning to allow connections from the user, but once set it should be possible to safely use that user on a dedicated machine.

**Comment by luceos** [comment] 2016-12-20 14:20
Might also be some issues with creating databases/users from the package. Not sure though as I haven't tested the package on postgres.

**Comment by jdbolts** [comment] 2016-12-20 14:26
| Role Name   |                                       Attributes                                         | Member of |
|---------------|-----------------------------------------------------------------|---------------|
| default_user | Superuser, Create role, Create DB, Replication, Bypass RLS |           {}         |
| postgres       | Superuser, Create role, Create DB, Replication, Bypass RLS |           {}         |

Above is my list of users for my PgSQL installation. the `default_user` is the one i am using for this installation and it is currently sat on a dedicated machine. The `default_user` has identical permissions and attributes as the `postgres` user.

I will keep checking the configuration of the RDBMS to see if there are any restrictions.

**Comment by humbugz** [comment] 2016-12-20 20:15
Unfortunately there will be additional issues with using this package with PGSQL: the DatabaseConnection class's create() method uses "create database if not exists", which isn't valid SQL to Postgres. The DB creation is also wrapped in a transaction, which is not supported by PGSQL either. 

I've been experimenting with a few hacks to see where else I may run into issues and to see if adding PG support would be straight forward or not. It's simple enough to hack DatabaseConnection.php (though it's obviously bad to modify the project files directly!). Some simple updates allow it to create the tenant DB's, but I'm currently working on ways to grant the permissions correctly under PGSQL. From there it'll be interesting to see if there are other compatibility issues or not!

**Comment by luceos** [comment] 2016-12-20 20:35
Right, version 3.x (in dev) will be easier to extend/modify. In 2.x the connection class in some situations is still hardcoded (unresolved through ioc), I noticed this flaw a while back and decided to rethink all of it completely. I will take into consideration flexible database drivers for the new version. In the meantime feel free to report further issues.

**Comment by humbugz** [comment] 2016-12-20 21:21
@Luceos, out of curiosity do your plans for v3 include breaking changes? Or is it likely to be a (more-or-less) drop-in replacement for v2?

I ask as the reason I'm investigating v2's compatibility with PgSQL is we're about to embark on a new project and are evaluating this package to kick-start the multi-tenancy aspects.

Thanks!

**Comment by luceos** [comment] 2016-12-20 22:15
3.x is a complete rewrite and will not work with a 1.x or 2.x implementation at all, guaranteed. Aside from being event driven, I plan (and work on) making as much as possible interchangeable with whatever logic the implementation requires. I'll push the latest changes to this repository so you can check for yourselves.

[3.x tree](https://github.com/hyn/multi-tenant/tree/3.x)

**Comment by jdbolts** [comment] 2016-12-21 09:54
Is there any time-frame on when the 3.x branch will be available to use?

**Comment by luceos** [comment] 2016-12-21 10:01
Not really no. I had planned on releasing it a while ago, way before adoption of 2.x gained momentum. But circumstances left me without the time to continue my efforts. I expect to release 3.x somewhere early next year though, not sure if that's a comfort 😊

**Comment by jdbolts** [comment] 2016-12-21 11:06
@humbugz is it possible you could share your implementation for postgres?

@Luceos i will keep watching the repo :+1:

**Comment by humbugz** [comment] 2016-12-21 13:45
@bolts1 I wouldn't call it a real implementation at this point... Just started it the other day actually, and it currently consists of making bad in-line hacks to the existing code. My intent is to get more familiar with the code and identify where there may be other PgSQL incompatibilities. See if it's a logical starting point for our project or not.

That said, with a v3 in the near future, I'm more inclined to wait and review that instead. Even if it's not feature complete it may be a better starting point since we're starting from scratch of this project anyway.

 @Luceos, would you be willing to post an alpha version of 3.x in whatever state it's currently in? It's possible we could end up using it as part of our project and offering back any additions we make should you find them useful to include.

**Comment by luceos** [comment] 2016-12-21 14:25
@humbugz that alpha is already up: https://github.com/hyn/multi-tenant/tree/3.x

But it's not functional, you might be able to read through it and run tests to see what it does. I plan to take your comments at heart and will make sure there will be no hardcoded MySQL anymore, perhaps if one can drop-in a custom db driver adapter to run specific tenant queries, that might solve driver compatibility.

**Comment by humbugz** [comment] 2016-12-21 16:35
Thanks @Luceos, I'd missed that was posted. I'll take a look!

**Comment by luceos** [comment] 2016-12-22 08:50
Just for both your information: https://github.com/hyn/multi-tenant/issues/185

**Comment by luceos** [comment] 2017-05-04 12:17
3.x now can work with psql :) during db creation for tenants

**Comment by luceos** [comment] 2017-05-10 14:25
Okay, stable in gitlab CI. Closing.

**Closed as completed by luceos** 2017-05-10 14:25 UTC
Labels: feature
