### ISSUE TITLE
  Is there an out-of-the-box one?

### ISSUE THREAD

**Issue by opjklu** [hyn/multi-tenant#814] opened 2019-06-12 05:03 UTC
For example, when deployed, it can be used without writing code.

**Comment by ArlonAntonius** [comment] 2019-06-12 07:39
Hi @opjklu,

What do you mean with "used without writing code"?
At this moment there's no out-of-the-box solution where you don't have to code anything at all. We do make it very easy and really limit the amount of coding you need to do in order to make your application multi-tenant.

**Comment by krunonovosel** [comment] 2019-06-13 10:45
Duplicate of #

**Closed as completed** 2020-01-31 11:50 UTC
Labels: support
