### ISSUE TITLE
An argument with name "class" already exists

### ISSUE THREAD

**Issue by jonquintero** [hyn/multi-tenant#988] opened 2021-03-10 18:04 UTC
Hi, I did a composer update and now I got this error

An argument with name "class" already exists. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\LogicException(code: 0): An argument with name \"class\" already exists. at C:\\laragon\\www\\crm-tenant\\proto-crm-back\\vendor\\symfony\\console\\Input\\InputDefinition.php:99)
[stacktrace]
#0 C:\\laragon\\www\\crm-tenant\\proto-crm-back\\vendor\\symfony\\console\\Command\\Command.php(387): Symfony\\Component\\Console\\Input\\InputDefinition->addArgument(Object(Symfony\\Component\\Console\\Input\\InputArgument))
#1 C:\\laragon\\www\\crm-tenant\\proto-crm-back\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Concerns\\HasParameters.php(24): Symfony\\Component\\Console\\Command\\Command->addArgument('class', 2, 'The class name ...', NULL)
#2 C:\\laragon\\www\\crm-tenant\\proto-crm-back\\vendor\\hyn\\multi-tenant\\src\\Traits\\MutatesSeedCommands.php(38): Illuminate\\Console\\Command->specifyParameters()
#3 C:\\laragon\\www\\crm-tenant\\proto-crm-back\\vendor\\hyn\\multi-tenant\\src\\Providers\\Tenants\\ConnectionProvider.php(71): Hyn\\Tenancy\\Database\\Console\\Seeds\\SeedCommand->__construct(Object(Illuminate\\Database\\DatabaseManager))
#4 C:\\laragon\\www\\crm-tenant\\proto-crm-back\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(826): Hyn\\Tenancy\\Providers\\Tenants\\ConnectionProvider->Hyn\\Tenancy\\Providers\\Tenants\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#5 C:\\laragon\\www\\crm-tenant\\proto-crm-back\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(712): Illuminate\\Container\\Container->build(Object(Closure))
#6 C:\\laragon\\www\\crm-tenant\\proto-crm-back\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(841): Illuminate\\Container\\Container->resolve('Hyn\\\\Tenancy\\\\Dat...', Array, true)
#7 C:\\laragon\\www\\crm-tenant\\proto-crm-back\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(651): Illuminate\\Foundation\\Application->resolve('Hyn\\\\Tenancy\\\\Dat...', Array)
#8 C:\\laragon\\www\\crm-tenant\\proto-crm-back\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(826): Illuminate\\Container\\Container->make('Hyn\\\\Tenancy\\\\Dat...', Array)
#9 C:\\laragon\\www\\crm-tenant\\proto-crm-back\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Application.php(260): Illuminate\\Foundation\\Application->make('Hyn\\\\Tenancy\\\\Dat...')
#10 C:\\laragon\\www\\crm-tenant\\proto-crm-back\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Application.php(274): Illuminate\\Console\\Application->resolve('Hyn\\\\Tenancy\\\\Dat...')
#11 C:\\laragon\\www\\crm-tenant\\proto-crm-back\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\ServiceProvider.php(396): Illuminate\\Console\\Application->resolveCommands(Array)
#12 C:\\laragon\\www\\crm-tenant\\proto-crm-back\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Application.php(151): Illuminate\\Support\\ServiceProvider->Illuminate\\Support\\{closure}(Object(Illuminate\\Console\\Application))
#13 C:\\laragon\\www\\crm-tenant\\proto-crm-back\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Application.php(74): Illuminate\\Console\\Application->bootstrap()
#14 C:\\laragon\\www\\crm-tenant\\proto-crm-back\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(330): Illuminate\\Console\\Application->__construct(Object(Illuminate\\Foundation\\Application), Object(Illuminate\\Events\\Dispatcher), '8.32.1')
#15 C:\\laragon\\www\\crm-tenant\\proto-crm-back\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(129): Illuminate\\Foundation\\Console\\Kernel->getArtisan()
#16 C:\\laragon\\www\\crm-tenant\\proto-crm-back\\artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 {main}
"}

**Comment by jonquintero** [comment] 2021-03-10 18:06
I'm using laravel 8

**Comment by drbyte** [comment] 2021-03-10 20:06
Is this a duplicate of #987 ?

**Comment by jonquintero** [comment] 2021-03-11 09:43
Ok it seems the same issue

**Comment by jonquintero** [comment] 2021-03-12 11:05
Hi @luceos @ArlonAntonius  look at this problem, this new change https://github.com/laravel/framework/issues/36557 broke the package

**Comment by ArlonAntonius** [comment] 2021-03-12 16:05
@jonquintero Noted this to our team yesterday and we are aware, we want to look at this asap. We're also still working on the PHP8 compatibility. Always open to a PR in order to fix this though.

**Comment by bkintanar** [comment] 2021-03-14 20:53
dupped by #987

**Closed as completed by bkintanar** 2021-03-14 20:53 UTC
