### ISSUE TITLE
I can't load any non tenant website e.g. admin dashboard

### ISSUE THREAD

**Issue by gkarugi** [hyn/multi-tenant#357] opened 2017-12-27 06:09 UTC
Everything is working as expected with tenant websites. How can I set the system connection as the default on the fly when the base URL (base URL should hold the admin panel) is requested?

-Edited

**Comment by Thijmen** [comment] 2017-12-27 10:33
You could create a middleware for that, you can look into our middleware for identification hostnames and implement it as you want it :-)

**Comment by gkarugi** [comment] 2017-12-27 21:20
The tenant host names are the ones saved in the database, but the URL which should hold the main website and admin dashboard is not saved in the database. Can you point me in the right direction on how I can use a middleware to accomplish this?

**Comment by luceos** [comment] 2017-12-31 12:59
Can't your dashboard models not simply connect to the system database by applying that trait?

**Comment by gkarugi** [comment] 2018-01-16 20:37
it seems there is a global middleware which enforces the multitenancy. I have installed the application on azure. When I use their automatic deployment from a git repository tool, I am getting the following error :

> @php artisan package:discover

In Connection.php line 664:        
                                                         
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'masterdb.hostnam  
  es' doesn't exist (SQL: select * from `hostnames` where `fqdn` = uza.scm.az  
  urewebsites.net limit 1)      
                                               
In PDOConnection.php line 79:      
                                                                  
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'masterdb.hostnam  
  es' doesn't exist 

In PDOConnection.php line 77:

     Script @php artisan package:discover handling the post-autoload-dump event returned with error 
     code 1       
                                                                    
     SQLSTATE[42S02]: Base table or view not found: 1146 Table 'masterdb.hostnam  
    es' doesn't exist

**Comment by gkarugi** [comment] 2018-01-16 21:03
@luceos , I can successfully use the system connection trait.

I get the Exception Target [Hyn\Tenancy\Contracts\CurrentHostname] is not instantiable. when I try accessing any other FQDN that is not linked to a tenant.

Lets take a sub domains approach for creating tenants :

When a tenant is first created, their app is located on tenant1.domain.com, when someone tries accessing domain.com the Target [Hyn\Tenancy\Contracts\CurrentHostname] is not instantiable. exception is given.

**Comment by luceos** [comment] 2018-01-17 08:11
@gkarugi how is your tenant identification set up? Can you post your tenancy.php configuration?

**Comment by gkarugi** [comment] 2018-01-17 15:27
I have the set the following to env
` TENANCY_AUTO_HOSTNAME_IDENTIFICATION = false`

````
<?php
use Hyn\Tenancy\Database\Connection;

return [
     'models' => [
    
        'customer' => \App\Models\Models\Customer::class,

        'hostname' => \App\Models\Hostname::class,

        'website' => \App\Models\Website::class
    ],
    'website' => [
        'disable-random-id' => false,

        'random-id-generator' => Hyn\Tenancy\Generators\Uuid\ShaGenerator::class,

        'uuid-limit-length-to-32' => env('LIMIT_UUID_LENGTH_32', false),

        'disk' => null,

        'auto-create-tenant-directory' => true,

        'auto-rename-tenant-directory' => true,

        'auto-delete-tenant-directory' => env('AUTO_DELETE_TENANT_DIRECTORY', false),

        'cache' => 10,
    ],
    'hostname' => [
      
        'default' => env('TENANCY_DEFAULT_HOSTNAME'),
       
        'auto-identification' => env('TENANCY_AUTO_HOSTNAME_IDENTIFICATION', true),

        'early-identification' => env('TENANCY_EARLY_IDENTIFICATION', false),

        'abort-without-identified-hostname' => true,

        'cache' => 10,
    ],
    'db' => [
       
        'default' => env('TENANCY_DEFAULT_CONNECTION'),
       
        'system-connection-name' => env('TENANCY_SYSTEM_CONNECTION_NAME', Connection::DEFAULT_SYSTEM_NAME),
        'tenant-connection-name' => env('TENANCY_TENANT_CONNECTION_NAME', Connection::DEFAULT_TENANT_NAME),

        'tenant-division-mode' => env('TENANCY_DATABASE_DIVISION_MODE', 'database'),

        'password-generator' => Hyn\Tenancy\Generators\Database\DefaultPasswordGenerator::class,

        'tenant-migrations-path' => database_path('migrations/tenant'),

        'tenant-seed-class' => false,

        'auto-create-tenant-database' => true,

        'auto-rename-tenant-database' => true,

        'auto-delete-tenant-database' => env('AUTO_DELETE_TENANT_DATABASE', false),
    ],
    'folders' => [
        'config' => [
           
            'enabled' => true,

            'blacklist' => ['database', 'tenancy', 'webserver'],
        ],
        'routes' => [
            'enabled' => true,

            'prefix' => null,
        ],
        'trans' => [
            'enabled' => true,

            'override-global' => true,

            'namespace' => 'tenant',
        ],
        'vendor' => [
            'enabled' => true,
        ],
        'media' => [
            
            'enabled' => true,
        ]
    ]
];

<?php

namespace App\Providers;

use Hyn\Tenancy\Database\Connection;
use Hyn\Tenancy\Environment;
use Hyn\Tenancy\Models\Hostname;
use Illuminate\Database\QueryException;
use Illuminate\Support\ServiceProvider;

class TenancyServiceProvider extends ServiceProvider
{
    public function register() {

    }
    public function boot()
    {
        $connection = app(Connection::class);
        if (file_exists(base_path('tenancy.json'))) {
            try {
                $hostname = Hostname::on($connection->systemName())->where('fqdn', request()->getHttpHost())->first();
                //set connection to the hostname's tenant if the hostname exists
                if (!is_null($hostname)) {
                    $this->app->make(Environment::class)->hostname($hostname);
                }
            }
            catch (QueryException $e) {
                \Log::notice($e->getMessage());
            }
        }
    }
}

**Comment by fletch3555** [comment] 2018-01-17 16:43
Github commenting hint: use triple-backticks (```) before and after code blocks.  Single backticks only work for single lines

**Comment by gkarugi** [comment] 2018-01-17 18:08
@fletch3555 thanks for the hint.

**Comment by luceos** [comment] 2018-01-18 08:11
@gkarugi if you allow auto identification, but don't set early identification. Identification is done inside the package Service Provider by resolving the `Environment` class out of ioc. Trying to use the CurrentHostname in another service provider then only works if the package service provider is loaded first. You can solve this by setting early identification, but I'm not too sure that works with your code there. Please note this is unrelated to the current issue. Please create a new issue to continue discussing this.

**Comment by fletch3555** [comment] 2018-01-18 13:13
@luceos, your description of what's happening is accurate, but I'm not convinced it's unrelated to this issue.  I was attempting a very similar task (admin subdomain that doesn't rely on tenancy).  The problem is that `CurrentHostname` is resolved regardless of what setting (early identification or auto detection) you have.  It's done in `HostnameActions` middleware, which is prepended to the middleware stack by the tenancySP, which means it's applied to every request, regardless of whether you're intending to use tenancy or not.

I've been working on a way to choose when to load this middleware.  Current thought is having the service provider add it as named route middleware and making users apply it to their tenancy routes(maybe add it to RouteSP... maybe wrap everything in a route group... many ways to do it). But I'm not sure I like that from the perspective of a new user setting up the package for the first time.  Maybe doing it this way just isn't default and gets toggled by a config? I don't know, any suggestions/opinions?

**Comment by luceos** [comment] 2018-01-18 13:29
Hm, so HostnameActions requires CurrentHostname, even though the Environment wasn't loaded yet? That makes any installation without (custom) early identification misbehave 😞 

Is this correct @fletch3555 ?

**Comment by gkarugi** [comment] 2018-01-18 14:15
@fletch3555 you are right. I have tested it by setting early identification to true(by default it is false) and auto identification to false(by default it is true) but `CurrentHostname ` is still being resolved. 

I was thinking on similar lines, to let the user themselves to apply a tenancy middleware  to the routes which require tenancy.

**Comment by fletch3555** [comment] 2018-01-18 14:52
@luceos, yes that's correct, but there's a little more to it.  Even with those settings enabled, non-tenant sites will 404 because there's no hostname record.


I plan to keep both settings set to true, but had them off to test something when i noticed this behavior.  I don't want to maintain a "dummy" hostname record for non-tenent sites.  There should be a way to differentiate tenant routes from non-tenant routes and only do hostname detention where appropriate.  I've seen this requested quite a few times recently. It feels much more intuitive than blindly applying it to everything

**Comment by luceos** [comment] 2018-02-07 10:21
@fletch3555 would you be able to review dev-5.x to see whether it solves this current issue?

**Comment by luceos** [comment] 2018-06-04 10:22
Fallback articles in the docs should help with this.

**Closed as completed by luceos** 2018-06-04 10:22 UTC
