### ISSUE TITLE
Questions About modules & tenancy

### ISSUE THREAD

**Issue by n-ramos** [hyn/multi-tenant#186] opened 2017-01-13 09:56 UTC
Hey guys, im sorry for my bad english but i would like to know how can i create a tenant app with some modules like ping pong modules for some customers website,

For example i have 2 customers, one need invoice system but not the other

I have module invoice with ping pong but i want enable it for the other, how can i do that, any ideas ?

**Comment by luceos** [comment] 2017-01-13 10:55
@SpeedUpFramework okay so there are several different ways to approach this.

1. Add the module (let's call this logic) globally, including routes etc. Add some middleware that tests whether the activated Tenant has some configuration (you can add your own system database table with columns `tenantId`, `configuration`, `setting` for instance). In case the routes matches the module and it is not active for that tenant simply return a 404.
2. Add the logic globally, but the routes only for the tenants that can use it.
3. Add the logic locally using a symlink - I'd advice against that.

In case you have lots of these 'modules' you might want to implement something as proposed in no. 1. I haven't heard of anyone doing this yet, so feel free to ask questions or consult me when running into issues.

**Comment by n-ramos** [comment] 2017-01-13 11:01
Hello @Luceos Thanks for this approach, i think it's a good start about this, i gonna try this when i can, i ask questions if i need. Thanks again.

**Comment by luceos** [comment] 2017-01-13 11:17
Feel free to comment when you have anything else. As this is not a bug or feature, I'm closing this.

**Closed as completed by luceos** 2017-01-13 11:17 UTC

**Comment by n-ramos** [comment] 2017-01-13 12:28
With ping pong, i can do that: Module::find('name'); can i do that in specific route for a specific website ? 
With this method => $module->enable();

**Comment by luceos** [comment] 2017-01-13 15:03
I have no visibility what Module is. It's not part of this package, as such I cannot foresee whether that call will work.
