### ISSUE TITLE
[Feature Request] Interchangeable models

### ISSUE THREAD

**Issue by aaronfahey** [hyn/multi-tenant#563] opened 2018-07-30 05:59 UTC
__Description of your feature__

Currently, the package allows the use of custom models, provided you implement the correct contracts. However, we are still currently bound to the use of the `hostnames` table, and `websites` table, this generally would suit the majority of the package's users, however it would be really cool if these were able to be configurable.

 In my situation, I'd like to rename the `Website` model to `Clinic`, as my system is currently modelling clinics. It's more of a readability issue, rather than the function of the package.

If I rename the `Website` model and change the table that it looks at, I get a tonne of errors because in some parts of the framework it is hardcoded to `websites`.

---

__Proposed behavior__

- Provide functionality that allows the configuration of table names. Perhaps we could somehow get the table from the model itself?

__Current behavior__

- Not possible

**Comment by luceos** [comment] 2018-07-30 09:04
If you explain where the tables are hardcoded I'll make sure to get those out. Hardcoded tables was never planned. They might have snuck in.

**Comment by aaronfahey** [comment] 2018-07-30 10:31
@luceos sorry should have provided that information initially.

I have only found instances of hardcoded tables in the validator classes, see:

https://github.com/hyn/multi-tenant/blob/c7e36198d5bec6b016c5d0c8a54f547a681b0314/src/Validators/HostnameValidator.php#L22

https://github.com/hyn/multi-tenant/blob/c7e36198d5bec6b016c5d0c8a54f547a681b0314/src/Validators/HostnameValidator.php#L26

https://github.com/hyn/multi-tenant/blob/c7e36198d5bec6b016c5d0c8a54f547a681b0314/src/Validators/HostnameValidator.php#L31

https://github.com/hyn/multi-tenant/blob/c7e36198d5bec6b016c5d0c8a54f547a681b0314/src/Validators/HostnameValidator.php#L35

https://github.com/hyn/multi-tenant/blob/c7e36198d5bec6b016c5d0c8a54f547a681b0314/src/Validators/WebsiteValidator.php#L22-L26

**Comment by fletch3555** [comment] 2018-07-30 19:40
@MrFahey those make sense, as the validators are specific to those models.  Perhaps the issue is that the validator is still being applied to your custom model

**Comment by aaronfahey** [comment] 2018-07-30 22:01
@fletch3555 good point, perhaps we could somehow allow the ability to specify a validator for a given model?

**Comment by luceos** [comment] 2018-07-31 08:34
I like that idea; perhaps a method on the model that returns the validator, we could add that to the contract too..

**Comment by MrFahey** [comment] 2018-09-01 08:13
Closing in favour of #563.

**Comment by aaronfahey** [comment] 2018-09-01 08:14
Closing in favour of #600.

**Closed as completed** 2018-09-26 11:22 UTC
Labels: bug, good first issue
